language: java
sudo: false
install: true
jdk:
 - oraclejdk8

before_install:
  - chmod +x mvnw
cache:
  directories: 
    - .autoconf
    - '$HOME/.m2'  
script:
  - ./mvnw clean package
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: expertus-api
  on:
    branch: master